= Cahier des Charges - Application CheckYourMood
:author: Franck Silvestre
:title-page: true
:icons: font
:toc: left
:sectnums:

== Introduction

La startup _CheckYourMood_ souhaite développer une première version de son application Web éponyme.

Cette application doit permettre à un utilisateur enregistré sur la plateforme d'indiquer son humeur à différents moments de la journée afin de pouvoir disposer de visualisations sur son humeur au fil du temps en fonction de différents paramètres comme la période, le type d'humeur, etc.

Ce document présente les exigences produits et projets permettant de livrer à la startup la première version de son projet en temps et en heure.

Dans la suite du document, les termes "application" ou "plateforme" désignent de manière indifférente l'application Web _CheckYourMood_.

== Exigences fonctionnelles

Les exigences fonctionnelles sont décrites au format User Story. Elles sont regroupées en _features_. 

La section dictionnaire décrit les notions clés mobilisées par l'application.

=== Dictionnaire

.Humeur
Une humeur décrit un état psychologique d'une personne. Dans l'application CheckYourMood, une humeur est fournie par un utilisateur et est caractérisée par :

* un libellé (par exemple "Colère", "Joie", etc.)
* un emoji
* une date et heure
* un élément de context facultatif

Les libellés possibles pour décrire une humeur sont fournis en <<_annexes>>. Ils sont issus des travaux de recherche de Alan S. Cowen et Dacher Keltner. 

=== _Feature_ F001 "Gestion de mon compte" 

Cette feature comprend les fonctionnalités relatives à la gestion de compte par un utilisateur.

.User stories
[cols="1,1,2"]
|===
|Identifiant exigence |Titre | Description

|US001
|Création d'un compte
|En tant qu'utilisateur, +
Je veux m'enregistrer sur la plateforme, +
Pour bénéficier des services de suivi de mon humeur.

|US002
|Authentification
|En tant qu'utilisateur ayant un compte sur la plateforme, +
Je veux m'authentifier avec un login et un mot de passe, +
Pour avoir accès à mes services personnalisés.

|US003
|Modification de mes données personnelles
|En tant qu'utilisateur authentifié, +
Je veux modifier mes données personnelles, +
Pour maintenir à jour mes données en cas de changements dans ma vie

|US004
|Désinscription
|En tant qu'utilisateur authentifié, +
Je veux supprimer mon compte de la plateforme, +
Pour ne pas laisser trainer des informations personnelles sur une plateforme dont je ne veux plus bénéficier des services. 
|===

=== _Feature_  F002 "Gestion de mes humeurs" 

Cette feature comprend les fonctionnalités relatives à la gestion de son humeur par un utilisateur.

.User stories
[cols="1,1,2"]
|===
|Identifiant exigence |Titre | Description

|US005
|Saisie d'une humeur
|En tant qu'utilisateur authentifié, +
Je veux ajouter une humeur à tout instant de la journée, +
Pour obtenir à terme le plus d'information possible sur mon humeur au fil du temps.

|US005
|Consultation de mes humeurs
|En tant qu'utilisateur authentifié, +
Je veux consulter la liste de mes humeurs suivant différents critère (date, libellé, etc.), +
Pour me faire une idée de mes humeurs dans le temps.
|===

=== _Feature_ F003 "Visualisations de mes humeurs"

En tant qu'utilisateur, +
Je veux disposer de plusieurs visualisations, +
Pour m'aider à suivre mes humeurs facilement dans le temps

Les visualisations devront être paramétrables mais le besoin n'est pas plus explicité à ce stade. La MOE devra être force de proposition sur les US à développer.


== Exigences techniques

=== Architecture de l'application

[cols="1,2,2"]
|===
|Identifiant exigence |Périmètre | Exigences

|ARC001
|Architecture 3-tiers
|L'application est une application Web s'appuyant sur une architecture 3-tiers.

|ARC002
|Modele Vue Contrôleur
|L'application est une application conçue sur la base du _design pattern_ MVC.
|===

=== Environnements techniques

[cols="1,2,2"]
|===
|Identifiant exigence |Périmètre | Exigences

|TECH001
|SGBD Relationnel
|MySQL version 8 ou supérieure

|TECH002
|Langages de programmation _back-end_
|Php version 8 ou supérieure, 

|TECH003
|Langages de programmation _front-end_
|HTML 5, librairie Bootstrap version 5 ou supérieure pour les apports CSS et Javascript

|TECH004
|Gestion de version de code source
|Git version 2.32 ou supérieure
|===

=== Contraintes de développement

[cols="1,2,2"]
|===
|Identifiant exigence |Périmètre | Exigences

|DEV001
|Tests automatisés
|Le code des services métier développés dans le Modèle de l'application font l'objet d'une couverture de code par les tests automatisés supérieure à 80% 
|===

    Peut être complété par des contraintes issues d'outils d'analyse statique de code.

=== Contraintes d'exploitation

[cols="1,2,2"]
|===
|Identifiant exigence |Périmètre | Exigences

|EXPL001
|Temps de réponse
|Toutes les pages du site doivent s'afficher en moins de 0,1 secondes dans l'environnement de développement

|EXPL002
|Sauvegarde données quotidienne
|Tous les jours à 3h du matin, un dump de la base de données doit être exécuté et envoyé sur un serveur de sauvegarde via le protocole SFTP ou équivalent.

|===

== Annexes

=== Annexe 1 - Libellés des humeurs

. Admiration
. Adoration
. Appréciation esthétique
. Amusement
. Colère
. Anxiété
. Émerveillement
. Malaise (embarrassement)
. Ennui
. Calme (sérénité)
. Confusion
. Envie (craving)
. Dégoût
. Douleur empathique
. Intérêt étonné, intrigué
. Excitation (montée d'adrénaline)
. Peur
. Horreur
. Intérêt
. Joie
. Nostalgie
. Soulagement
. Romance
. Tristesse
. Satisfaction
. Désir sexuel
. Surprise

Pour une version interactive (en anglais) : https://s3-us-west-1.amazonaws.com/emogifs/map.html# 