= Cahier des Charges - Application Festiplan
:author: Franck Silvestre
:title-page: true
:icons: font
:toc: left
:sectnums:

== Introduction

La startup _Festiplan_ souhaite développer une première version de son application Web éponyme.

Cette application doit permettre la gestion de la planification des spectacles (pièces de théatre, concerts) sur les différentes scènes mise à disposition par les organisateurs du festival.

Ce document présente les exigences produits et projets permettant de livrer à la startup la première version de son projet en temps et en heure.

Dans la suite du document, les termes "application" ou "plateforme" désignent de manière indifférente l'application Web _Festiplan_.

== Exigences fonctionnelles

Les exigences fonctionnelles sont décrites au format User Story. Elles sont regroupées en _features_. 

La section dictionnaire décrit les notions clés mobilisées par l'application.
La section rôle spécifie les rôles endossables par les utilisateurs dans la plateforme. 

=== Dictionnaire

.Festival
Un festival regroupe un ensemble de prestations (spectacles) se déroulant sur différents emplacements dans une zone géographique délimitée. Un festival se déroule sur une période finie de quelques jours. Un festival est porté par un organisateur du festival pouvant être composé d'une équipe de personnes. Un festival est caractérisé par :

* un nom
* Une description (1000 caractères max)
* Une illustation optionnelle (une image au format GIF, JPEG ou PNG ayant pour taille max (800x600))
* Une date de début et une date de fin
* Au moins une catégorie (musique, théatre, cirque, danse, projection de film)
* Liste de scènes
* Liste des membres de l'équipe organisatrice
* Un responsable du festival (appartenant à la l'équipe organisatrice).

.Scène
Une scène est un lieu pouvant accueillir un spectacle du festival.
Une scène est caractérisée par :

* Un festival
* Un nom
* Une taille (petite, moyenne, grande)
* Un nombre de spectateurs maximum
* les coordonnées GPS de son emplacement

.Spectacle
Un spectacle est une prestation de durée limitée se produisant sur une scène du festival et est caractérisé par :

* Un titre
* Une description (1000 caractères max)
* Une illustation optionnelle (une image au format GIF, JPEG ou PNG ayant pour taille max (800x600))
* Une durée en minutes
* au moins une catégorie (concert, pièce de théatre, cirque, danse, projection de film)
* Taille de surface de scène requise (petite, moyenne, grande)
* Liste des intervenants sur scène (acteurs, musiciens, danseurs)
* Liste des intervenants hors scène (régisseurs son et lumière, etc.)
* Un responsable du spectacle.

.Utilisateur
Un utilisateur est une personne disposant d'un compte sur la plateforme. Un utilisateur est caractérisé par :

* Un nom
* Un prénom
* Une adresse email
* Un login
* Un mot de passe


=== Rôles

.Responsable de festival
Un responsable de festival dispose de tous les droits relatifs  aux festivals dont il a la responsabilité. Il peut créer des festivals et modifier/supprimer les festivals dont il est responsable. Un responsable de festival dispose de tous les droits d'un _organisateur de festival_.

.Organisateur de festival
Un organisateur de festival peut modifier les caractéristiques d'un festival dont il est organisateur. Il peut donc participer à la planification du programme des spectacles.

.Responsable de spectacle
Un responsable de spectacle dispose de tous les droits relatifs  aux spectacles dont il a la responsabilité. Il peut créer des spectacles et modifier/supprimer les spectacles dont il est responsable.

=== _Feature_ F001 "Gestion des comptes" 

Cette feature comprend les fonctionnalités relatives à la gestion des comptes par un utilisateur.

.User stories
[cols="1,1,2"]
|===
|Identifiant exigence |Titre | Description

|F001US001
|Création de compte
|En tant que  futur utilisateur de la plateforme, +
Je peux créer un compte sur l'application, +
Afin de bénéficier des services de la plateforme.

|F001US002
|Authentification
|En tant qu'utilisateur ayant un compte sur la plateforme, +
Je veux m'authentifier avec un login et un mot de passe, +
Pour avoir accès à mes services personnalisés.

|F001US003
|Modification de mes données personnelles
|En tant qu'utilisateur authentifié, +
Je veux modifier mes données personnelles, +
Pour maintenir à jour mes données en cas de changements dans ma vie

|F001US004
|Désinscription
|En tant qu'utilisateur authentifié, +
Je veux supprimer mon compte de la plateforme, +
Pour ne pas laisser trainer des informations personnelles sur une plateforme dont je ne veux plus bénéficier des services. 
|===

=== _Feature_ F002 "Gestion des festivals (hors planification)" 

Cette feature comprend les fonctionnalités relatives à la gestion de festivals par un utilisateur.

.User stories
[cols="1,1,2"]
|===
|Identifiant exigence |Titre | Description

|F002US001
|Création d'un festival
|En tant qu'utilisateur authentifié, +
Je peux créer un nouveau festival dont je suis responsable sur l'application, +
Afin de gérer les caractéristiques et la planification du festival.


|F002US002
|Ajout d'un organisateur au festival
|En tant que responsable de festival, +
Je peux affecter un nouvel organisateur du festival en renseignant le login ou l'email du nouvel organisateur  , +
Afin de pourvoir gérer à plusieur les caractéristiques et la planification du festival.

|F002US003
|Modification des caractéristiques d'un festival
|En tant qu'organisateur d'un festival, +
Je peux modifier les caractéristiques du festival, +
Afin de pouvoir reporter les changements relatifs à ce festival en lien avec des aléas.

|F002US004
|Suppression d'un festival
|En tant que responsable d'un festival, +
Je peux supprimer le festival, +
Afin de ne pas laisser trainer des données qui ne sont plus utiles sur la plateforme.

|F002US003
|Accès à la liste de mes festivals
|En tant qu'organisateur d'au moins un festival, +
Je peux accéder à la liste des festivals dont je suis organisateur, +
Afin d'accéder facilement à un festival sur lequel je dois travailler'.

|===


== Exigences techniques

=== Architecture de l'application

[cols="1,2,2"]
|===
|Identifiant exigence |Périmètre | Exigences

|ARC001
|Architecture 3-tiers
|L'application est une application Web s'appuyant sur une architecture 3-tiers.

|ARC002
|Séparation des responsabilités
|L'application est structurée de telle sorte que les différentes responsabilités de l'application (accès aux bases de données, présentations, navigations, features, etc.) soient implantés dans des dossiers différents et donc dans des fichiers différents (l'utilisation d'un _framework_ n'est pas requise).
|===

=== Environnements techniques

[cols="1,2,2"]
|===
|Identifiant exigence |Périmètre | Exigences

|TECH001
|SGBD Relationnel
|MySQL version 8 ou supérieure

|TECH002
|Langages de programmation _back-end_
|Php version 8 ou supérieure, 

|TECH003
|Langages de programmation _front-end_
|HTML 5, librairie Bootstrap version 5 ou supérieure pour les apports CSS et Javascript

|TECH004
|Gestion de version de code source
|Git version 2.32 ou supérieure
|===


=== Contraintes d'exploitation

[cols="1,2,2"]
|===
|Identifiant exigence |Périmètre | Exigences

|EXPL001
|Temps de réponse
|Toutes les pages du site doivent s'afficher en moins de 0,1 secondes dans l'environnement de développement

|EXPL002
|Sauvegarde données quotidienne
|Tous les jours à 3h du matin, un dump de la base de données doit être exécuté et envoyé sur un serveur de sauvegarde via le protocole SFTP ou équivalent.

|===
