= Cahier des Charges - Application Festiplan
:author: Franck Silvestre
:title-page: true
:icons: font
:toc: left
:sectnums:

== Introduction

La startup _Festiplan_ souhaite développer une première version de son application Web éponyme.

Cette application doit permettre la gestion de la planification des spectacles (pièces de théatre, concerts) sur les différentes scènes mise à disposition par les organisateurs du festival.

Ce document présente les exigences produits et projets permettant de livrer à la startup la première version de son projet en temps et en heure.

Dans la suite du document, les termes "application" ou "plateforme" désignent de manière indifférente l'application Web _Festiplan_.

== Exigences fonctionnelles

Les exigences fonctionnelles sont décrites au format User Story. Elles sont regroupées en _features_. 

La section dictionnaire décrit les notions clés mobilisées par l'application.

=== Dictionnaire

.Festival
Un festival regroupe un ensemble de prestations (spectacles) se déroulant sur différents emplacements dans une zone géographique délimitée. Un festival se déroule sur une période finie de quelques jours. Un festival est porté par un organisateur du festival pouvant être composé d'une équipe de personnes. Un festival est caractérisé par :

* un nom
* Une description (1000 caractères max)
* Une illustation optionnelle (une image au format GIF, JPEG ou PNG ayant pour taille max (800x600))
* Une date de début et une date de fin
* Au moins une catégorie (musique, théatre, cirque, danse, projection de film)
* Liste de scènes
* Liste des membres de l'équipe organisatrice
* Un responsable du festival (appartenant à la l'équipe organisatrice).

.Scène
Une scène est un lieu pouvant accueillir un spectacle du festival.
Une scène est caractérisée par :

* Un festival
* Un nom
* Une taille (petite, moyenne, grande)
* Un nombre de spectateurs maximum
* les coordonnées GPS de son emplacement

.Spectacle
Un spectacle est une prestation de durée limitée se produisant sur une scène du festival et est caractérisé par :

* Un titre
* Une description (1000 caractères max)
* Une illustation optionnelle (une image au format GIF, JPEG ou PNG ayant pour taille max (800x600))
* Une durée en minutes
* au moins une catégorie (concert, pièce de théatre, cirque, danse, projection de film)
* Taille de surface de scène requise (petite, moyenne, grande)
* Liste des intervenants sur scène (acteurs, musiciens, danseurs)
* Liste des intervenants hors scène (régisseurs son et lumière, etc.)
* Un responsable du spectacle.

=== _Feature_ F001 "Gestion des comptes et des rôles" 

Cette feature comprend les fonctionnalités relatives à la gestion de compte par un utilisateur.

.User stories
[cols="1,1,2"]
|===
|Identifiant exigence |Titre | Description

|US001
|Création d'un compte
|En tant qu'utilisateur, +
Je veux m'enregistrer sur la plateforme, +
Pour bénéficier des services de suivi de mon humeur.

|US002
|Authentification
|En tant qu'utilisateur ayant un compte sur la plateforme, +
Je veux m'authentifier avec un login et un mot de passe, +
Pour avoir accès à mes services personnalisés.

|US003
|Modification de mes données personnelles
|En tant qu'utilisateur authentifié, +
Je veux modifier mes données personnelles, +
Pour maintenir à jour mes données en cas de changements dans ma vie

|US004
|Désinscription
|En tant qu'utilisateur authentifié, +
Je veux supprimer mon compte de la plateforme, +
Pour ne pas laisser trainer des informations personnelles sur une plateforme dont je ne veux plus bénéficier des services. 
|===


== Exigences techniques

=== Architecture de l'application

[cols="1,2,2"]
|===
|Identifiant exigence |Périmètre | Exigences

|ARC001
|Architecture 3-tiers
|L'application est une application Web s'appuyant sur une architecture 3-tiers.

|ARC002
|Séparation des responsabilités
|L'application est structurée de telle sorte que les différentes responsabilités de l'application (accès aux bases de données, présentations, navigations, features, etc.) soient implantés dans des dossiers différents et donc dans des fichiers différents (l'utilisation d'un _framework_ n'est pas requise).
|===

=== Environnements techniques

[cols="1,2,2"]
|===
|Identifiant exigence |Périmètre | Exigences

|TECH001
|SGBD Relationnel
|MySQL version 8 ou supérieure

|TECH002
|Langages de programmation _back-end_
|Php version 8 ou supérieure, 

|TECH003
|Langages de programmation _front-end_
|HTML 5, librairie Bootstrap version 5 ou supérieure pour les apports CSS et Javascript

|TECH004
|Gestion de version de code source
|Git version 2.32 ou supérieure
|===


=== Contraintes d'exploitation

[cols="1,2,2"]
|===
|Identifiant exigence |Périmètre | Exigences

|EXPL001
|Temps de réponse
|Toutes les pages du site doivent s'afficher en moins de 0,1 secondes dans l'environnement de développement

|EXPL002
|Sauvegarde données quotidienne
|Tous les jours à 3h du matin, un dump de la base de données doit être exécuté et envoyé sur un serveur de sauvegarde via le protocole SFTP ou équivalent.

|===
